name: Compilar e fazer deploy em producao

on:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  build:
    name: 'gerando artefato'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd ./app
          mvn -B clean package -DskipTests

      - name: Upload Lambda JAR
        uses: actions/upload-artifact@v3
        with:
          name: lambda_sts-jar
          path: ./app/target/lambda_sts-1.0.0.jar

  terraform:
    needs: [build]
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-producao.yml
    secrets: inherit
