name: 'DESTROY infra producao'
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'

permissions:
  contents: read

jobs:
  build:
    name: "preparando destroy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd ./app
          mvn -B clean package -DskipTests

      - name: Upload Lambda JAR
        uses: actions/upload-artifact@v3
        with:
          name: lambda_sts-jar
          path: ./app/target/lambda_sts-1.0.0.jar


  terraform:
    needs: [build]
    name: 'deploy em producao'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2

        with:
          name: lambda_sts-jar
          path: ./app/target/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: Terraform Init
        run: |
          cd ./infra
          terraform init -reconfigure

      - name: Terraform Plan
        run: |
          cd ./infra
          terraform plan -input=false

      - name: Terraform Apply
        run: |
          cd ./infra
          terraform destroy -auto-approve    
